# enemy_color: "red"
enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: false

#####-----ROI-----#####
roi: 
  x: 500
  y: 400
  width: 500
  height: 500

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 1.5 # degree
pitch_offset: -0.5 # degree
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.050 # s
low_speed_delay_time: 0.015 # s

#####-----shooter参数-----#####
first_tolerance: 100 # 近距离射击容差，degree
second_tolerance: 100 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 2
gain: 16
vid_pid: "2bdf:0001"

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

# 重投影误差: 0.1488px
camera_matrix: [1775.1300101814929, 0, 710.22041588791421, 0, 1777.9427175568535, 599.38373307949621, 0, 0, 1]
distort_coeffs: [-0.081907189655237952, 0.14019999270205855, -0.0012264127665053185, 0.0014292255962000792, 0]

# 相机同理想情况的偏角: yaw1.81 pitch0.16 roll-0.00 degree
R_camera2gimbal: [-0.03152275773856239, 0.0027095830669845509, 0.99949936163269204, -0.99950303430107212, -9.8404785402239625e-05, -0.031522606799691932, 1.2942398579498703e-05, -0.99999632423129503, 0.0027113384873522772]
t_camera2gimbal: [0.13895789074180098, 0.066620637390426771, 0.028079650211170731]


#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----buff_detector参数-----#####
model: "assets/yolov8_buff.xml"
classify_model: "assets/tiny_resnet.onnx"

#####-----buff_aimer参数-----#####
aim_time: 0.150         # s
wait_time: 0.300        # s
command_fire_gap: 0.080 # s
predict_time: 0.150     # s
