#状态向量的协方差矩阵 13x13
P0: [1,1,1,1,1,1,1,64,64,64,64,64,64]
#线速度噪声向量 3x1
V0: [1e-3,1e-3,1e-3]
#角速度噪声向量 3x1
Omega0: [1e-3,1e-3,1e-3]
#预测过程噪声的协方差矩阵 6x6
Q0: [1e-3,1e-3,1e-3,1e-3,1e-3,1e-3]

camera_matrix: [1295.4665175006589, 0, 655.71498478800618, 
                0, 1297.2591156991834, 506.21320670125334, 
                0, 0, 1]

#####-----神经网络参数-----#####
classify_model: assets/tiny_resnet.onnx
model_path: assets/last.xml
device: AUTO
min_confidence: 0.8

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.1944px
camera_matrix: [1295.4665175006589, 0, 655.71498478800618, 0, 1297.2591156991834, 506.21320670125334, 0, 0, 1]
distort_coeffs: [-0.48599095566724387, 0.23999516531343185, -0.00029018466701866776, -0.00083639963030895752, 0]

# 相机同理想情况的偏角: yaw-2.64 pitch-3.20 roll-0.77 degree
# 标定板到世界坐标系原点的水平距离: 1.45 m
# 标定板同竖直摆放时的偏角: yaw90.85 pitch8.54 roll-0.32 degree
R_camera2gimbal: [0.046736929626455238, -0.055211941324114208, 0.99738021884550865, -0.99881598162461238, -0.016078770676278314, 0.0459141370909011, 0.013501639172863072, -0.99834518813322415, -0.055898041744621867]
t_camera2gimbal: [0.27420934670256336, 0.0098763306562371159, 0.043798385984197351]