# enemy_color: "red"
enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 2.5 # degree -2.5
pitch_offset: 3.1 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.030 # s
low_speed_delay_time: 0.015 # s

#####-----shooter参数-----#####
first_tolerance: 8 # 近距离射击容差，degree
second_tolerance: 5 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 4
gain: 16.9
vid_pid: "2bdf:0001"

# -1  0  0
#  0 -1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.1077px
camera_matrix: [1783.1352455869924, 0, 712.25232126543733, 0, 1791.4823798103048, 573.49956992910597, 0, 0, 1]
distort_coeffs: [-0.078807913877987926, 0.15574954821119635, 0.00073002566867448159, 0.001210731408502146, 0]

# 相机同理想情况的偏角: yaw2.50 pitch-4.72 roll2.13 degree
R_camera2gimbal: [-0.046688242480313003, -0.080470535390043937, 0.99566294545299772, -0.99822331730532432, 0.040697652227314141, -0.043519075026227511, -0.037019141022629175, -0.99592579745542498, -0.082227666637953334]
t_camera2gimbal: [0.14816386746905794, 0.096371592867113956, 0.025967577445711799]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM1"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####

fire_thresh: 0.05
yaw_inertia: 7e-2
yaw_torque_max: 6
Q_yaw: [10000, 50]
R_yaw: [10]
pitch_inertia: 9e-3
pitch_torque_max: 3
Q_pitch: [100000, 50]
R_pitch: [10]

#####-----buff_detector参数-----#####
detect:
  contrast: 1
  brightness: 
    blue: -120
    red: -50
  brightness_threshold:
    blue: 120
    red: 90
  morphology_size:
    blue: 3
    red: 3
  dilate_size: 1
  # canny_low_threshold: 100
  # canny_high_threshold: 180
  # approx_epsilon: 1.0
  R_contours_min_area: 200
  R_contours_max_area: 600
  fanblades_head_contours_min_area: 3000
  fanblades_head_contours_max_area: 8000
  fanblades_body_contours_min_area: 1000
  fanblades_body_contours_max_area: 4000
  standard_fanblade_path: ./assets/standard_fanblade.jpg

#####-----buff_aimer参数-----#####
aim_time: 0.150         # s
wait_time: 0.800        # s
command_fire_gap: 0.080 # s
predict_time: 0.210     # s